<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hellotravel</groupId>
        <artifactId>hello-travel</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>hello-travel-adaptor</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.hellotravel</groupId>
            <artifactId>hello-travel-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hellotravel</groupId>
            <artifactId>hello-travel-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hellotravel</groupId>
            <artifactId>hello-travel-model</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hellotravel</groupId>
            <artifactId>hello-travel-application</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
        </dependency>
        <dependency>
            <groupId>io.milvus</groupId>
            <artifactId>milvus-sdk-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
        </dependency>
    </dependencies>
</project>
